name: CI Pipeline with Auto Tagging

on:
 workflow_call:
 
jobs:
  check-files:
     runs-on: ubuntu-latest
     steps:
      - name: Download changes.txt
        uses: actions/download-artifact@v3
        with:
          name: changes
      - name: Display changes.txt
        run: cat changes.txt
