name: CI Pipeline with Auto Tagging

on:
 workflow_call:
 
jobs:
  check-files:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: cat Changes
        run: |
         cat changes.txt
