name: CI Pipeline with Auto Tagging

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: cat Changes
        run: |
         cat changes.txt
