name: CI Pipeline with Auto Tagging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
     if: github.event_name == 'push' && github.ref_name == 'main'

    steps:
      - name: check ref name
        run: |
          echo "${{ github.ref_name }}" 

